quarters = int(input("How many quarters? "))
dimes = int(input("How many dimes? "))
nickels = int(input("How many nickels? "))
pennies = int(input("How many pennies? "))
print("You have", quarters*0.25 + dimes*0.1 + nickels*0.05 + pennies*0.01, "dollars")
